name: build-test

on:
  push:
    branches:
      - master
    # file paths to consider in the event. Optional; defaults to all.
#    paths:
#      - 'src/**'
#      - 'pom.xml'


jobs:
  build-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn compile --file pom.xml
    - name: Test with Maven
      run: mvn test --file pom.xml
