name: unit-tests

on:
  push:
    paths:
      - "src/*"
      - ".github/workflows/*"

  pull_request:
    branches:
      master
    paths:
      - "src/*"
      - ".github/workflows/*"


jobs:
  build-test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn compile --file pom.xml
      - name: Test with Maven
        run: mvn test --file pom.xml