name: deploy-package

on:
  release:
    types:
      - created

jobs:
  build-deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn compile --file pom.xml
      - name: Deploy with Maven
        env:
          GITHUB_TOKEN: ${{ secrets.githubtoken }}
        run: |
          mkdir ~/.m2 -p
          echo "<settings xmlns=\"http://maven.apache.org/SETTINGS/1.0.0\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:schemaLocation=\"http://maven.apache.org/xsd/settings-1.0.0.xsd\"><servers><server><id>github</id><username>bonnal-enzo</username><password>${GITHUB_TOKEN}</password></server></servers></settings>" > ~/.m2/settings.xml
          mvn deploy -Dregistry=https://maven.pkg.github.com/bonnal-enzo -Prelease -DskipTests -Dmaven.wagon.http.pool=false
